### ISSUE TITLE
Add IAM role to Terraform scripts

### ISSUE THREAD

**Issue by adolski** [medusa-project/book-tracker#53]
The Book Tracker's IAM role is not defined in the Book Tracker's Terraform scripts. We should make sure that it is defined there instead of making changes via the AWS web console.

**Comment by gaurijo** [comment]
Since the output of this didn't actually change anything, do I still need to run a `terraform apply` or is that just an extra step in this case?

**Comment by adolski** [comment]
I don't know if it's required or not, but I'd run it anyway. It couldn't hurt. I don't know enough about how Terraform works--t might update some kind of internal state

**Comment by gaurijo** [comment]
You're right, I think it does update or do something with the` terraform.lock.hcl.` 

I ran an `apply` for the demo service, and just pushed up a PR for the same thing with `prod service`. 

After that's merged I'll run an apply for prod and then I plan to` deploy to demo and prod`again so everything is up to date (unless it's not needed since this was already added via aws console a few days ago)

**Comment by gaurijo** [comment]
Everything has been redeployed successfully and all branches (develop/demo/prod) are up to date now.
